# Generated by Django 5.0 on 2024-01-21 23:25

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CalendarEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField()),
                ("currency", models.CharField(max_length=3)),
                ("impact", models.CharField(max_length=32)),
                ("event", models.CharField(max_length=128)),
                ("forecast", models.CharField(max_length=32)),
                ("previous", models.CharField(max_length=32)),
            ],
        ),
    ]
