# Generated by Django 5.0 on 2024-01-21 23:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="calendarevent",
            unique_together={("timestamp", "currency", "impact", "event")},
        ),
    ]
