# Generated by Django 5.0 on 2024-01-04 01:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scanner", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockindex",
            name="symbol",
            field=models.CharField(default="", max_length=5, verbose_name="Symbol"),
            preserve_default=False,
        ),
    ]
