# Generated by Django 5.0 on 2024-01-04 05:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scanner", "0003_symbolrec_skip_discord_alerts"),
    ]

    operations = [
        migrations.AddField(
            model_name="symbolrec",
            name="yfinance_meta",
            field=models.JSONField(blank=True, null=True, verbose_name="YFinance Meta"),
        ),
    ]
