# Generated by Django 5.0 on 2024-01-06 10:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scanner", "0004_symbolrec_yfinance_meta"),
    ]

    operations = [
        migrations.CreateModel(
            name="NegatedReason",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reason",
                    models.IntegerField(
                        choices=[
                            (1, "RR Minimum"),
                            (2, "TFC Conflict"),
                            (3, "Magnitude Threshold"),
                            (4, "Gapping"),
                            (5, "Potential Outside Bar"),
                        ]
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="setup",
            name="negated_reasons",
        ),
        migrations.DeleteModel(
            name="SetupDev",
        ),
        migrations.AddField(
            model_name="setup",
            name="negated_reasons",
            field=models.ManyToManyField(blank=True, to="scanner.negatedreason"),
        ),
    ]
