# Generated by Django 5.0 on 2024-01-08 02:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("scanner", "0005_negatedreason_remove_setup_negated_reasons_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="setup",
            name="negated_reasons",
        ),
    ]
