# Generated by Django 5.0 on 2024-01-14 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scanner", "0008_negatedreason_setup_negated_reasons"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProviderMeta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provider_name", models.CharField(max_length=200)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("meta", models.JSONField(blank=True, null=True, verbose_name="Meta")),
                (
                    "main_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="provider_metas",
                        to="scanner.symbolrec",
                    ),
                ),
            ],
        ),
    ]
