# Generated by Django 5.0 on 2024-01-21 23:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scanner", "0010_rename_provider_name_providermeta_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="symbolrec",
            name="polygon_meta",
        ),
        migrations.RemoveField(
            model_name="symbolrec",
            name="schwab_meta",
        ),
        migrations.RemoveField(
            model_name="symbolrec",
            name="yfinance_meta",
        ),
        migrations.AlterField(
            model_name="symbolrec",
            name="exchange",
            field=models.CharField(
                choices=[
                    ("NYSE", "NYSE"),
                    ("POLYGON", "Polygon"),
                    ("BINANCE", "Binance"),
                    ("STOCK", "STOCK"),
                ],
                max_length=32,
                verbose_name="Exchange",
            ),
        ),
    ]
