# Generated by Django 5.0 on 2024-01-25 18:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scanner", "0011_remove_symbolrec_polygon_meta_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="symbolrec",
            name="is_index",
            field=models.BooleanField(default=False, verbose_name="Is Index"),
        ),
    ]
