# Generated by Django 3.2.13 on 2022-05-17 13:31

from django.db import migrations, models
import django.utils.timezone
import stratbot.users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='Is Staff?')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Potentially unselect this instead of deleting accounts.', verbose_name='Is Active?')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Joined')),
                ('realtime_alerts_channel_name', models.CharField(editable=False, help_text="This is a unique realtime alerts channel name for this `User`. We make this value to be at least relatively secure and not guessable so that, at the time of writing, only Pusher knows the value. Browser extensions, etc. and other Javascript scripts can see it, but we're not worried about that because you have to be authenticated with Pusher to send messages to the channel anyway. So, we could've just used the `pk`, but for ever so slightly more peace of mind and potential security improvements we generate a long random string instead just using some value derived from the `pk`.", max_length=40, unique=True, verbose_name='Realtime Alerts Channel Name')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
            managers=[
                ('objects', stratbot.users.models.UserManager()),
            ],
        ),
    ]
