# Generated by Django 4.2.6 on 2023-10-19 14:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile_image",
            field=models.ImageField(
                blank=True,
                help_text="Optional.",
                null=True,
                upload_to="users/profile_images",
                verbose_name="Profile Image",
            ),
        ),
    ]
